[tox]
requires =
    tox-uv>=1
runner = uv-venv-runner
envlist = py{310,311,312,313,314}-locale-{c,utf8}-poller-{poll,select},lint
isolated_build = True

[testenv]
setenv =
    locale-c: LANG=C
    locale-utf8: LANG=en_US.UTF-8
    poller-select: SH_TESTS_USE_SELECT=1
    poller-poll: SH_TESTS_USE_SELECT=0
    SH_TESTS_RUNNING=1
deps =
    pytest
    coverage
commands =
    pytest tests/ {posargs}

[testenv:lint]
deps =
    ruff
    rstcheck
commands =
    ruff check src/sh/ tests/
    ruff format --check src/sh tests/
    mypy src/sh/
    stubtest sh
    pyrefly coverage check src/sh
    rstcheck README.rst